# Generated by Django 5.2.6 on 2025-12-19 19:45

import django.db.models.deletion
import django.utils.timezone
import muestras.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda_envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(default=None, max_length=200, unique=True)),
                ('lugar', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('persona_contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_contacto', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Congelador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congelador', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura_minima', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura_maxima', models.CharField(blank=True, max_length=50, null=True)),
                ('localizacion_edificio', models.CharField(blank=True, max_length=50, null=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='congeladores/')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_estudio', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_estudio', models.CharField(max_length=100, unique=True)),
                ('descripcion_estudio', models.TextField(blank=True, null=True)),
                ('fecha_inicio_estudio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estudio', models.DateField(blank=True, null=True)),
                ('investigador_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('investigadores_asociados', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Investigadores'}, related_name='estudios_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_estudios_web', 'Puede ver estudios en la web'), ('can_add_estudios_web', 'Puede añadir estudios en la web'), ('can_change_estudios_web', 'Puede cambiar estudios en la web'), ('can_delete_estudios_web', 'Puede eliminar estudios en la web')],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=muestras.models.ruta_documentos)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateField(blank=True, null=True)),
                ('usuario_subida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudio', to='muestras.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_individuo', models.CharField(max_length=20)),
                ('nom_lab', models.CharField(max_length=100, unique=True)),
                ('id_material', models.CharField(blank=True, max_length=20, null=True)),
                ('volumen_actual', models.FloatField(blank=True, null=True)),
                ('unidad_volumen', models.CharField(blank=True, max_length=15, null=True)),
                ('concentracion_actual', models.FloatField(blank=True, null=True)),
                ('unidad_concentracion', models.CharField(blank=True, max_length=15, null=True)),
                ('masa_actual', models.FloatField(blank=True, null=True)),
                ('unidad_masa', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_extraccion', models.DateField(blank=True, null=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_inicial', models.CharField(blank=True, max_length=50, null=True)),
                ('centro_procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_actual', models.CharField(blank=True, choices=[('DISP', 'Disponible'), ('ENV', 'Enviada'), ('ENVP', 'Parcialmente enviada'), ('DEST', 'Destruida')], default='Disponible', max_length=50, null=True)),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muestras.estudio', to_field='nombre_estudio')),
            ],
            options={
                'permissions': [('can_view_muestras_web', 'Puede ver muestras en la web'), ('can_add_muestras_web', 'Puede añadir muestras en la web'), ('can_change_muestras_web', 'Puede cambiar muestras en la web'), ('can_delete_muestras_web', 'Puede eliminar muestras en la web')],
            },
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congelador', models.CharField(blank=True, max_length=50, null=True)),
                ('estante', models.CharField(blank=True, max_length=50, null=True)),
                ('posicion_rack_estante', models.CharField(blank=True, max_length=50, null=True)),
                ('rack', models.CharField(blank=True, max_length=50, null=True)),
                ('posicion_caja_rack', models.CharField(blank=True, max_length=50, null=True)),
                ('caja', models.CharField(blank=True, max_length=50, null=True)),
                ('subposicion', models.IntegerField(blank=True, null=True)),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizacion', to='muestras.muestra', to_field='nom_lab')),
            ],
            options={
                'permissions': [('can_view_localizaciones_web', 'Puede ver localizaciones en la web'), ('can_add_localizaciones_web', 'Puede añadir localizaciones en la web'), ('can_change_localizaciones_web', 'Puede cambiar localizaciones en la web'), ('can_delete_localizaciones_web', 'Puede eliminar localizaciones en la web')],
                'unique_together': {('congelador', 'estante', 'posicion_rack_estante', 'rack', 'posicion_caja_rack', 'caja', 'subposicion')},
            },
        ),
        migrations.CreateModel(
            name='historial_localizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('usuario_asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('localizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_localizaciones', to='muestras.localizacion')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_localizaciones', to='muestras.muestra')),
            ],
        ),
        migrations.CreateModel(
            name='historial_estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_estudios', to='muestras.estudio')),
                ('usuario_asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estudios', to='muestras.muestra')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_enviado', models.FloatField()),
                ('unidad_volumen_enviado', models.CharField(max_length=15)),
                ('concentracion_enviada', models.FloatField()),
                ('unidad_concentracion_enviada', models.CharField(max_length=15)),
                ('centro_destino', models.CharField(max_length=100)),
                ('lugar_destino', models.CharField(max_length=100)),
                ('fecha_envio', models.DateField(default=django.utils.timezone.now)),
                ('usuario_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='muestras.muestra')),
            ],
        ),
        migrations.CreateModel(
            name='registro_destruido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_destruido', to='muestras.muestra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
