# Generated by Django 5.2.6 on 2025-12-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacion',
            name='subposicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
