# Generated by Django 5.2.6 on 2025-12-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0002_alter_localizacion_subposicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congelador',
            name='congelador',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('congelador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estantes', to='muestras.congelador')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('posicion_rack_estante', models.CharField(max_length=50)),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='muestras.estante')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('posicion_caja_rack', models.CharField(max_length=50)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='muestras.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Subposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('vacia', models.BooleanField(default=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subposiciones', to='muestras.caja')),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='subposicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muestras.subposicion'),
        ),
        migrations.AlterField(
            model_name='historial_localizaciones',
            name='localizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_localizaciones', to='muestras.subposicion'),
        ),
        migrations.AddConstraint(
            model_name='estante',
            constraint=models.UniqueConstraint(fields=('congelador', 'numero'), name='unique_estante_por_congelador'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('estante', 'numero'), name='unique_rack_por_estante'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('rack', 'numero'), name='unique_caja_por_rack'),
        ),
        migrations.AddConstraint(
            model_name='subposicion',
            constraint=models.UniqueConstraint(fields=('caja', 'numero'), name='unique_subposicion_por_caja'),
        ),
    ]
