# Generated by Django 5.2.6 on 2025-12-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0003_alter_congelador_congelador_estante_rack_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congelador',
            name='congelador',
            field=models.CharField(max_length=50),
        ),
    ]
