# Generated by Django 5.2.6 on 2025-12-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0004_alter_congelador_congelador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congelador',
            name='congelador',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='estante',
            name='congelador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estantes', to='muestras.congelador', to_field='congelador'),
        ),
    ]
