# Generated by Django 5.2.6 on 2025-12-25 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0005_alter_congelador_congelador_alter_estante_congelador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localizacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historial_localizaciones',
            name='localizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_localizaciones', to='muestras.localizacion'),
        ),
    ]
