# Generated by Django 5.2.6 on 2025-12-25 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0006_alter_localizacion_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='subposicion',
        ),
        migrations.AddField(
            model_name='subposicion',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muestras.muestra'),
        ),
    ]
