# Generated by Django 5.2.6 on 2025-12-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0007_remove_muestra_subposicion_subposicion_muestra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacion',
            name='posicion_caja_rack',
        ),
        migrations.RemoveField(
            model_name='localizacion',
            name='posicion_rack_estante',
        ),
    ]
