# Generated by Django 5.2.6 on 2025-12-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0008_remove_localizacion_posicion_caja_rack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subposicion',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestra', to='muestras.muestra'),
        ),
    ]
