# Generated by Django 5.2.6 on 2025-12-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0009_alter_subposicion_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subposicion',
            name='muestra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subposicion', to='muestras.muestra'),
        ),
    ]
