# Generated by Django 5.2.6 on 2025-12-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0010_alter_subposicion_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='estado_actual',
            field=models.CharField(blank=True, choices=[('DISP', 'Disponible'), ('ENV', 'Enviada'), ('ENVP', 'Parcialmente enviada'), ('DEST', 'Destruida')], default='DISP', max_length=50, null=True),
        ),
    ]
